version: '3'
services:
  postgres-development:
    image: postgres:11.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: language_lesson_development
    volumes:
      - ./data/devel:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  postgres-test:
    image: postgres:11.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: language_lesson_test
    volumes:
      - ./data/test:/var/lib/postgresql/data/
    ports:
      - 15432:5432
    depends_on:
      - postgres-development
      