default: &default
  adapter: postgresql
  host: 127.0.0.1
  encoding: unicode
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  port: 5432
  database: language_lesson_development

test:
  <<: *default
  port: 15432
  database: language_lesson_test